apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::248183845077:role/eksctl-cicd-demo-nodegroup-ng-1-NodeInstanceRole-16C6Y2HYTPM57
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::248183845077:role/service-role/codebuild-projectdemo-service-role
      username: codebuild-projectdemo-service-role
    - groups:
      - system:masters
      rolearn: arn:aws:iam::248183845077:role/CodeBuildKubectlRole
      username: CodeBuildKubectlRole
     - groups:
      - system:masters
      rolearn: arn:aws:iam::248183845077:role/role-name
      username: role-name
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::248183845077:role/eksctl-cicd-demo-nodegroup-ng-1-NodeInstanceRole-16C6Y2HYTPM57\n  username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n  rolearn: arn:aws:iam::248183845077:role/CodeBuildKubectlRole\n  username: CodeBuildKubectlRole\n- groups:\n  - system:masters\n  rolearn: arn:aws:iam::248183845077:role/CodeBuildKubectlRole\n  username: CodeBuildKubectlRole\n - groups:\n  - system:masters\n  rolearn: arn:aws:iam::248183845077:role/role-name\n  username: role-name\n  - system:masters\n","mapUsers":"[]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2022-05-16T19:03:04Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"15984","uid":"90720530-cdc8-4232-921c-9555828942fd"}}
  creationTimestamp: "2022-05-16T19:03:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "176094"
  uid: 90720530-cdc8-4232-921c-9555828942fd